export default {
	"unauthorized": "Pastikan anda sudah masuk.",
	"loginSuccess": "Berhasil masuk.",
	"loginFail": "Kata sandi salah.",
	"userNotFound": "Pengguna tidak ditemukan.",
	"created": "Berhasil dibuat.",
	"createdFail": "Gagal dibuat.",
	"updated": "Berhasil diperbarui.",
	"updatedFail": "Gagal diperbarui.",
	"delete": "Berhasil dihapus.",
	"deleteFail": "Berhasil dihapus.",
	"formFail": "Submit gagal.",
	"validationEmail": "Email tidak valid.",
	"validationEmpty": "Inputan tidak boleh kosong.",
	"validationConfirmPassword": "Konfirmasi password tidak sesuai.",
	"validationUsernameTaken": "Username sudah digunakan.",
	"validationEmailTaken": "Email sudah digunakan.",
}